version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: yarn start:dev gateway
    env_file: 
      - './apps/gateway/.env'
    ports:
      - "3004:3004"
    volumes:
      - ".:/usr/src/app"
    networks:
      - my-network
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    command: yarn start:dev orders
    env_file: 
      - './apps/orders/.env'    
    ports:
      - "3005:3005"
    volumes:
      - ".:/usr/src/app"
    networks:
      - my-network
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: yarn start:dev auth
    env_file: 
      - './apps/auth/.env'    
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
